name: Speedrun
version: 0.0.1
main: de.hglabor.speedrun.Speedrun
api-version: 1.16

commands:
  next:
    description: Skips the phase
    usage: /next
    permission: group.admin
  speedrun-reload:
    description: Reloads the speedrun config
    usage: /speedrun-reload
    permission: group.admin
  loadstructures:
    description: Loads the speedrun structures
    usage: /loadstructures
    permission: group.admin
  renew:
    description: Renew
    usage: /renew